// Developer Express Code Central Example:
// How to remove colors from color collection in ColorPickUpEdit
// 
// I have created an example that illustrates how to add the RemoveColorByName
// method, which allows you to remove a color with a specific name in a specific
// tab from ColorPickEdit.
// 
// RemoveColorByName is an overloaded method that takes
// the name of the list from which to delete a color as its first parameter, and
// the name or list of color names to be removed as the second parameter.
// 
// You can find sample updates and versions for different programming languages here:
// http://www.devexpress.com/example=E4361

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Q445945.Properties
{


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }
    }
}
